# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dasbd72
service: aws-management

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-1
  architecture: arm64
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ce:GetCostAndUsage"
      Resource: "*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    useDownloadCache: true

functions:
  get_cost:
    handler: account_cost_lambda/lambda_function.lambda_handler
    events:
      - http:
          path: /cost
          method: get
